import { Application } from '@/types';

const now = new Date();

export const mockApplications: Application[] = [
  {
    id: '1',
    company: 'Mercado Libre',
    position: 'Frontend Developer',
    status: 'Entrevista técnica',
    source: 'LinkedIn',
    appliedAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    technologies: ['React', 'Next.js', 'TypeScript', 'Tailwind'],
    modality: 'Remoto',
    seniority: 'Semi Senior',
    notes: 'Hablar de performance y optimización en Next.js',
  },
  {
    id: '2',
    company: 'Google',
    position: 'Software Engineer',
    status: 'Guardada',
    source: 'Página empresa',
    appliedAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    technologies: ['React', 'TypeScript', 'Node.js'],
    modality: 'Híbrido',
    seniority: 'Senior',
    notes: 'Requiere relocation. Investigar beneficios.',
  },
  {
    id: '3',
    company: 'Globant',
    position: 'React Developer',
    status: 'Oferta',
    source: 'Referido',
    appliedAt: new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    technologies: ['React', 'Redux', 'Jest'],
    modality: 'Remoto',
    seniority: 'Semi Senior',
    salary: 'USD 3500',
  },
  {
    id: '4',
    company: 'Startup X',
    position: 'Fullstack Developer',
    status: 'Rechazada',
    source: 'Workana',
    appliedAt: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    technologies: ['Next.js', 'Supabase', 'Tailwind'],
    modality: 'Remoto',
    notes: 'No les alcanzó el budget para la posición.',
  },
  {
    id: '5',
    company: 'YPF',
    position: 'Frontend Engineer',
    status: 'Aplicada',
    source: 'LinkedIn',
    appliedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    technologies: ['React', 'Angular'],
    modality: 'Híbrido',
    location: 'Buenos Aires',
  }
];
